### ISSUE TITLE
Tests do not pass with fresh master

### ISSUE THREAD

**Issue by lazd** [ftlabs/ftdomdelegate#59]
I did a fresh `npm install`, pulled master, and ran `grunt buster`. I get the following errors:

```
  TypeError: 'undefined' is not a function (evaluating 'Delegate.prototype.handle.bind(this)')
    at Delegate (./build/dom-delegate.js:9)  Exception should be thrown when no handler is specified in Delegate#on

  ReferenceError: Can't find variable: assert
    at ./test/tests/delegateTest.js:285
```

The first is due to the fact that PhantomJS does not support `Function.prototype.bind()`.

**Comment by orangemug** [comment]
@lazd this was fixed in PR #81, please reopen if you have any further issues.
