### ISSUE TITLE
TypeError: 'undefined' is not a function (evaluating 'Delegate.prototype.handle.bind(this)') in Konacha

### ISSUE THREAD

**Issue by ryana** [ftlabs/ftdomdelegate#70]
Hey guys,

This library seems to work fine in the browser, but when I run automated tests in Konacha I'm getting this very confusing error:

    TypeError: 'undefined' is not a function (evaluating 'Delegate.prototype.handle.bind(this)')

It's saying that `Delegate.prototype.handle` is not defined when it's called from the constructor. This might fall under the purview of someone else's problem (eg. Konacha, PhantomJS, etc...) but I wanted to run it by you guys here first in case there was some obvious answer staring me in the face.

FWIW, even though I understand why it's being done, I've never written (or seen) this done inside a constructor:
`this.handle = Delegate.prototype.handle.bind(this);`

So perhaps this is a naive question and my JS-fu is failing me here.

Thanks!

**Comment by ryana** [comment]
Making this change addresses the issue for me:

```
  var _s = this;
  var _h; 
  /** @type function() */
  this.handle = function(e) {
    _h = _h || Delegate.prototype.handle.bind(_s);
    _h(e);
  }
```

But I honestly don't understand why....

**Comment by RangerMauve** [comment]
The problem isn't that `Delegate.prototype.handle` is undefined, it's that `Function.prototype.bind` doesn't seem to be defined. I'm not really sure about the details of Konacha, but my guess is that it's not running in an ES5 environment.

**Comment by ryana** [comment]
Oh right good point. That was staring me right in the face. What's odd is that the .bind call works when wrapped in the closure....

**Comment by RangerMauve** [comment]
You know what, I really have no idea. Is it behaving properly after the change you made?

**Comment by ryana** [comment]
Yeah. We can just close this and leave it for Google to find and maybe it'll help out someone else. Probably something weird to do with the order of how Konacha/Chai/Sinon/etc loads the environment.
