### ISSUE TITLE
Error on uglification

### ISSUE THREAD

**Issue by albell** [ftlabs/ftdomdelegate#72]
Did a fresh `npm install`, got a few deprecation warnings about fs-watch-tree and buffer-browserify. Then this error on `grunt` default:

![domdelegate-error-on-uglify](https://cloud.githubusercontent.com/assets/1142025/8815518/10792728-2fcf-11e5-82e0-47a1d21d555a.png)

**Comment by orangemug** [comment]
@albell I had the same warnings before the merge of PR #81. I'll close the issue please let me know if you have any further problems

**Comment by albell** [comment]
@orangemug Thanks for your perseverance. I might take another look at this. I have to say I'm nervous about yoking any of my work to a project that takes over a year to fix a totally broken build. Ultra-lightweight alternatives to jQuery et al are great in theory, but not when they aren't given basic maintenance.
